# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5312ee163c09338f350e697359a1f1b3648128f753720e03e110b76e6b3f2f6dbda729b074e048f979f7b3c28261b8b15a743215f003068f9984910d1ff9420a

test:
  secret_key_base: 01ff6387a80cbfe11e7dc777f82efa54a8a86b321e7922cc34990c392d70bca0c298b9fb150914fbbed94709083af695e93ef598c436a0ed8b8ec9efa242c88e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
